## Basic Functions

In [1]:
import numpy as np
a=np.array([1,4,3,2,5])
type(a)

numpy.ndarray

In [3]:
a.dtype

dtype('int64')

In [4]:
a.shape

(5,)

In [7]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [8]:
np.empty((2,2)) #empty and zeros are not same 

array([[0., 0.],
       [0., 0.]])

In [9]:
a*a

array([ 1, 16,  9,  4, 25])

## Sclicing 

In [16]:
arr=np.array([3,4,5,7,7,88,2,1,0])


In [17]:
a=arr[3:6].copy()

In [18]:
a[0]=69

In [19]:
a

array([69,  7, 88])

In [20]:
arr #np is written in C so all are pointers so they are refering to arr hence they also reflect in arr
#if we change value of a  To avoid this copy() function 

array([ 3,  4,  5,  7,  7, 88,  2,  1,  0])

In [24]:
arr[5]

88