In [1]:
import numpy as np

In [2]:
 a=np.array([[1,2,3],
             [4,5,6]])

In [7]:
a.sum(axis=0)# axis agar 1 hoga to wha colums ko add karega aur 0 hoga to row ko sum kerega 

array([5, 7, 9])

In [9]:
b=np.array([[7,8,9],[4,5,6]])

In [15]:
np.dot(b,a.transpose())

array([[ 50, 122],
       [ 32,  77]])

In [14]:
len(dir(np)) #to find numpy builtin functions

622

In [16]:
np.cross(a,b) #return cross product of a,b,

array([[-6, 12, -6],
       [ 0,  0,  0]])

In [17]:
c=np.array([[9,5,8],
            [45,67,3]])

In [18]:
np.sort(c)

array([[ 5,  8,  9],
       [ 3, 45, 67]])

In [23]:
np.sort(c,kind='quiksort') #also write (c,axis=0) so that sort take place in all columns and 1 means in all solumns

array([[ 5,  8,  9],
       [ 3, 45, 67]])