In [1]:
import numpy as np

In [2]:
a=np.arange(7)

In [3]:
a

array([0, 1, 2, 3, 4, 5, 6])

In [18]:
b=np.array([2,43,5,6,7,88,4,89,8,7,6,5,4,3,2,4,5,7])
b=b.reshape(6,3)

In [19]:
b

array([[ 2, 43,  5],
       [ 6,  7, 88],
       [ 4, 89,  8],
       [ 7,  6,  5],
       [ 4,  3,  2],
       [ 4,  5,  7]])

In [20]:
np.argsort(b)# it will return the index of smallest number 

array([[0, 2, 1],
       [0, 1, 2],
       [0, 2, 1],
       [2, 1, 0],
       [2, 1, 0],
       [0, 1, 2]])

In [21]:
np.argmax(b)# also work on 2d array 

7

In [22]:
np.argmin(b)

0